Repository Diversion2k22/Embellish, pull requests merged in 2022-02, with the labels that each got.

#6 Alligned nav-bar from file navbar.html, and fixed syntax error on styles.css
  embellish-website/css/styles.css
  embellish-website/include/navbar.html
Labels: Diversion, Level 1

#2 Button animation
  HTML+CSS+JS/Buttons/button-animation/README.md
  HTML+CSS+JS/Buttons/button-animation/index.html
  HTML+CSS+JS/Buttons/button-animation/style.css
  HTML+CSS+JS/README.md
Labels: Diversion, Level 2

#11 Sign in form
  HTML+CSS+JS/Forms/Sign-In Form/README.md
  HTML+CSS+JS/Forms/Sign-In Form/index.html
  HTML+CSS+JS/Forms/Sign-In Form/style.css
  HTML+CSS+JS/README.md
Labels: Diversion, Level 2

#13 Glassmorphism footer icons
  HTML+CSS+JS/Footer/Glassmorphism Footer icons/README.md
  HTML+CSS+JS/Footer/Glassmorphism Footer icons/css/style.css
  HTML+CSS+JS/Footer/Glassmorphism Footer icons/index.html
  HTML+CSS+JS/README.md
Labels: Diversion, Level 2

#15 Ios spinner
  HTML+CSS+JS/Loader/IOS-Spinner/2022-02-13 23-07-33.mp4
  HTML+CSS+JS/Loader/IOS-Spinner/README.md
  HTML+CSS+JS/Loader/IOS-Spinner/index.html
  HTML+CSS+JS/Loader/IOS-Spinner/style.css
  HTML+CSS+JS/README.md
Labels: Diversion, Level 2

#19 404 error page
  HTML+CSS+JS/Background/404-Error-Page/README.md
  HTML+CSS+JS/Background/404-Error-Page/index.html
  HTML+CSS+JS/Background/404-Error-Page/style.css
  HTML+CSS+JS/README.md
Labels: Diversion, Level 2

#21 4 color loader
  HTML+CSS+JS/Loader/4-color-loader/README.md
  HTML+CSS+JS/Loader/4-color-loader/index.html
  HTML+CSS+JS/Loader/4-color-loader/style.css
  HTML+CSS+JS/README.md
Labels: Diversion, Level 2

#31 Added component json file
  embellish-website/css/styles.css
  embellish-website/js/component.js
  embellish-website/js/componentData.json
Labels: Diversion, Level 3
